global:
  scrape_interval: 5s # Scrape often for this demo

scrape_configs:
  - job_name: 'tinder-worker'
    static_configs:
      - targets: ['worker:8001']

  - job_name: 'tinder-api'
    static_configs:
      - targets: ['api:8000']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
